### ISSUE TITLE
How to run it on my own VPS?

### ISSUE THREAD

**Issue by Nickpicking** [dddddddddzzzz/OpenHeart#5]
I would love to add the emoji reaction you use (OpenHeart), but I am lost on how to implement it. I don’t use CloudFlare, nor Glitch; can I run it on my own little VPS? If so, how would I go to do that? TIA!

**Comment by Fastidious** [comment]
Piggy backing on this, as my question is the same. I have the three files: `package.json`, `server.js` (set port to 7777, changing `fastify.listen({ port: process.env.PORT, host: '0.0.0.0’ }` to `fastify.listen({ port: 7777, host: '0.0.0.0’ }`), and `open-heart.json` on my server on a directory. I have run `npm install`, and ran `node server.js`.

It will run, but I am not able to get anything usable out of it. Going to the address, it reads “missing prams”. Trying to pass something like on the example (https://openheart.fyi), renders a 415:

```
{"statusCode":415,"code":"FST_ERR_CTP_INVALID_MEDIA_TYPE","error":"Unsupported Media Type","message":"Unsupported Media Type: application/x-www-form-urlencoded"}
```

Help, pretty please! 🙏🏻

**Comment by muan** [comment]
@Nickpicking The Glitch code is just a node app. If you install node on your server you should be able to just copy that code.

> Trying to pass something like on the example (https://openheart.fyi), renders a 415:

@Fastidious I believe for fastify you'd need https://github.com/fastify/fastify-formbody to accept `application/x-www-form-urlencoded`.

Sorry for the delay folks.
